[build]
target = "riscv64gc-unknown-none-elf"

[net]
git-fetch-with-cli = true

[target.riscv64gc-unknown-none-elf]
runner = "../tools/runner"
rustflags = [
    "-Ccode-model=medium",
    "-Crelocation-model=static",
    "-Cforce-frame-pointers=yes",
    "-Clinker=riscv64-unknown-elf-ld",
    "-Clinker-flavor=ld",
    "-Clink-args=-T src/platform/riscv64/linker.ld",
    "-Clink-args=--no-dynamic-linker",
    "-Clink-args=-no-pie",
]
