[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tsrc/linker.ld",
    "-Clink-args=-z nognustack",
    "-Clink-args=--no-dynamic-linker",
    "-Ccode-model=medium",
    "-Crelocation-model=static",
    "-Cforce-frame-pointers=yes"
]

[net]
git-fetch-with-cli = true
